name: generate trophy image

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate trophy svg
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: Nandinisingh07
          file: dist/trophy.svg
          theme: radical
          no-background: true
          no-frame: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}